title: Eli LeChien
description: Showcasing my electrical engineering projects
url: "https://elilechien.com"
baseurl: ""

author:
  name: "Eli LeChien"
  email: "eliaslechien@gmail.com"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:name/
